[Paths]

# declare variable name for path to file or folder. Variable name here is what gets pulled into scipts.
# for my setup on Windows and with heavy use in SAP, I stick with using the '\\' between folder, sub folder, files names.
# file paths without files attached need to be ending with trailing '\\'
# see other file in folder for how this path gets oulled into scripts via .ini file.

data_source_file_path = "X:\\Folder Name\\Sub Folder Name\\external_dataset.xlsx"
